# config.yaml
data:
  max_length: 128
  balance_strategy: "undersample"

model:
  base_model: "distilbert-base-multilingual-cased"
  num_classes: 3
  dropout_rate: 0.3
  embedding_dim: 384

training:
  batch_size: 16
  learning_rate: 0.00002
  num_epochs: 10
  warmup_steps: 500
  gradient_clip: 1.0
  early_stopping_patience: 3
  checkpoint_dir: "models/"

api:
  host: "0.0.0.0"
  port: 8000
  max_input_length: 512
  top_k_similar: 5

paths:
  raw_data: "data/raw/"
  processed_data: "data/processed/"
  embeddings: "data/embeddings/"
  models: "models/"